### PR TITLE
LoRA - Image Classification

### PR DESCRIPTION
**Pull request by alanahmet**
Jupyter notebook for image classification with LoRA

### CODE REVIEW

**Comment by alanahmet** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/shreydan/computer-vision-course/pull/9/discussion/#comment-1838707177) on ReviewNB
> 
> _shreydan commented on 2023-12-04T14:04:17Z_ ----------------------------------------------------------------
> 
> pretty good! I like the explanations as well, this is a good start.
> 
> Can you please clarify when the model is saved, if its the entire ViT model or just the LoRA parts?
> 
> I think another section for inference to show how to correctly load a peft model will also be beneficial just like [the HF tutorial you linked here](https://huggingface.co/docs/peft/task_guides/image_classification_lora#share-your-model-and-run-inference) and in addition to that perhaps also merging the peft model to the original model, somewhat like [this](https://discuss.huggingface.co/t/help-with-merging-lora-weights-back-into-base-model/40968/4)?

Thanks for the suggestions. Since we don't know the scope of the project, I dont want to complicate things but it makes sense. I will add another part for saving and loading both the peft and the original model.

**Comment by Anindyadeep** [comment]
@alanahmet, Awesome start man :smile: I added some comments, feel free to discuss or address them whenever you are free. Great job 🤗

**Comment by shreydan** [comment]
<p>yes this is due to changing the classifier head at the end, from Linear(in_ft,1000) to Linear(in_ft,37)</p><p> </p>

---

 <a href='https://app.reviewnb.com/shreydan/computer-vision-course/pull/9/discussion/#comment-1839192868'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by Anindyadeep — COMMENTED** [review]
@alanahmet, Awesome start man 😄 I added some comments, feel free to discuss or address them whenever you are free. Great job 🤗

**Comment by sezan92** [comment]
@alanahmet I will review after 2-3 days. hopefully that is fine. I think, to speed up the process, we should not ask all members for review. rather 2-3 is enough.

**Comment by alanahmet** [comment]
> hey @alanahmet what are your thoughts on using larger models than vit-base? LoRA shines when the models are large if I'm not wrong. What are your thoughts on using something like siglip/vit-large?

You are right LoRA shines on training large models However i think it would be more beneficial to use the same model and data across to similar tasks for users to comprehend more clearly parameters like memory training time accuracy ect.

**Comment by shreydan** [comment]
> You are right LoRA shines on training large models However i think it would be more beneficial to use the same model and data across to similar tasks for users to comprehend more clearly parameters like memory training time accuracy ect.

@alanahmet oh ok makes sense, with respect to comparison. :+1:

**Comment by sezan92** [comment]
<p>I suggest to add confusion metrics</p><p> </p>

---

 <a href='https://app.reviewnb.com/shreydan/computer-vision-course/pull/9/discussion/#comment-1839192817'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by sezan92 — COMMENTED** [review]
Reviewed in ReviewNB. commenting this to show in GitHub

**Comment by alanahmet** [comment]
<p>Since there are 37 classes I think it would be confusing</p>

---

 <a href='https://app.reviewnb.com/shreydan/computer-vision-course/pull/9/discussion/#comment-1839192817'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by alanahmet** [comment]
<p>Yes it was in my mind too. But I couldn't find one in hf. Can we use images from other sources or do you know of any tool for creating them from scratch ?</p>

---

 <a href='https://app.reviewnb.com/shreydan/computer-vision-course/pull/9/discussion/#comment-1839192840'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
