### PR TITLE
Fine-tuning ViT for object detection.

### PR DESCRIPTION
**Pull request by Anindyadeep**
This PR right now contains a jupyter notebook to fine-tune a ViT model for object detection.

```
🚧 Work in Progress 🚧
```

solves issue #10

### CODE REVIEW

**Comment by Anindyadeep** [comment]
This is still in draft mode. But feel free to add comments. Right things that are left are:

- adding the training and evaluation results. (Training on-going on colab)
- Adding the writings in md part of the notebook. Right now some wordings are done, but mostly
in the form of docstrings and comments.
- some general refinements of the notebook.

**Review by sezan92 — COMMENTED** [review]
I see that you are using a roboflow dataset . how about using dataset from huggingface? https://huggingface.co/docs/datasets/object_detection this will reduce the amount of code for preprocessing and readers can focus more on the object detection model

**Comment by Anindyadeep** [comment]
> I see that you are using a roboflow dataset . how about using dataset from huggingface? https://huggingface.co/docs/datasets/object_detection this will reduce the amount of code for preprocessing and readers can focus more on the object detection model

Thanks for the feedback :), Yep, so the reason, I have used a roboflow dataset is due to:

1. I do not want to use the same dataset the one used in the official docs, will not be unique. 
2. I went to some huggingface datasets, and saw most of the dataset are either very noisy (not good enough to fit in fine-tuning), or very large, which will not show the significance of smaller datasets fitting using fine-tuning. 
3. At the same time, I was also looking for a dataset with some impact (like real world use case), so that readers after doing this, can feel the importance.

For, all these reasons, I chose to go for roboflow datasets. Now, for the sake of this course, and to reduce the complexity, I am intending to do the following:

1. try to push this to hf hub, by giving proper citation to the dataset. We can do this if the dataset is good enough. Had a [discussions on permissions in discord]()
2. Then use the hf dataset as starter
3. Finally, I would like to keep an additional section how to make custom object detection dataset using huggingface datasets and roboflow.

**Comment by shreydan** [comment]
looks good! Would like more inline comments, docstrings etc and results!

**Comment by Anindyadeep** [comment]
> looks good! Would like more inline comments, docstrings etc and results!

Yep did, so so will write some more on this, but added the inference results.

**Pull request merged**
