### PR TITLE
Transfer learning - image classification

### PR DESCRIPTION
**Pull request by shreydan**
#2

### CODE REVIEW

**Review by Anindyadeep — APPROVED** [review]
Initial PR looks good to me. An addition can be adding a small docstrings inside the function telling about what the function does.

**Comment by Anindyadeep** [comment]
> @shreydan can you add NBreview app to this repository? this app helps us review Jupyter Notebooks.

Hey that would be awesome, I also faced some issues during review, and didn't knew something like that exists... Can review better using that.

**Comment by shreydan** [comment]
@sezan92 @Anindyadeep I've added reviewNB [https://app.reviewnb.com/shreydan/computer-vision-course/](https://app.reviewnb.com/shreydan/computer-vision-course/). Apparently, it'll be accessible via their own website, please let me know if there are any issues.

**Comment by shreydan** [comment]
> Initial PR looks good to me. An addition can be adding a small docstrings inside the function telling about what the function does.

Can you give an example? I was thinking, for all HF classes/methods, we can link them back to the docs.

**Review by sezan92 — APPROVED** [review]
Good enough as an initial update.

**Comment by sezan92** [comment]
@alanahmet @shreydan @Anindyadeep I think we can adopt the standard practice of merging the PR by the author themselves.

**Comment by shreydan** [comment]
> So we don't assign others as a reviewer anymore?

@alanahmet Sorry I think you missed the review, I had assigned everyone for review of this PR and we'll continue to do so for all PRs.

**Comment by sezan92** [comment]
> So we don't assign others as a reviewer anymore?

@alanahmet no. It means, when a PR is approved, the author of the PR him/herself will merge to the main branch.

**Pull request merged**
